// Generated by CoffeeScript 1.12.4
(function() {
  var app, bodyParser, express, index, logger, path;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  bodyParser = require('body-parser');

  index = require('./../routes/index');

  app = express();

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use('/api', index);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  app.use(function(err, req, res, next) {
    var ref;
    res.locals.message = err.message;
    res.locals.error = (ref = req.app.get('env') === 'development') != null ? ref : {
      err: {}
    };
    res.status(err.status || 500);
    return res.send('error');
  });

  module.exports = app;

}).call(this);

//# sourceMappingURL=app.js.map
