// Generated by CoffeeScript 1.12.4
(function() {
  angular.module('myApp').controller('RegistCtrl', [
    '$scope', function($scope) {
      console.log('注册的控制器');
      $scope.userEntity = {
        username: '',
        password: '',
        password2: ''
      };
      $scope.doRegist = function() {
        console.log($scope.userEntity);
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=registCtrl.js.map
